sudo: requred
dist: trusty

install:
 - sudo apt-get install -y qt5-default qttools5-dev-tools

script:
  - qmake "CONFIG+=test" QtOrm.pro
  - make
  - ./QtOrmTests/QueryModelsTest/tst_QueryModelsTestTest
  - ./QtOrmTests/QueryResultTest/tst_QueryResultTestTest

