include(Framework.pri)
COMMON_LIB_NAME = Common$${QT_MAJOR_VERSION}$${LIB_SUFFIX}
COMMON_FOLDER_NAME = Common
COMMON_INCLUDE = $$FRAMEWORK_INCLUDE/$$COMMON_FOLDER_NAME
COMMON_HEADERS = $$COMMON_INCLUDE/*.h

INCLUDEPATH += $$COMMON_INCLUDE
DEPENDPATH += $$INCLUDEPATH $$FRAMEWORK_INSTALL_LIBS

!contains(HEADERS, $$COMMON_HEADERS) HEADERS += $$COMMON_HEADERS

LIBS += -L$$FRAMEWORK_INSTALL_LIBS -l$$COMMON_LIB_NAME
