include($$FRAMEWORK/CommonInclude.pri)
QTORM_LIB_NAME = QtOrm$${QT_MAJOR_VERSION}$${LIB_SUFFIX}
QTORM_FOLDER_NAME = QtOrm
QTORM_INCLUDE = $$FRAMEWORK_INCLUDE/$$QTORM_FOLDER_NAME

INCLUDEPATH += $$QTORM_INCLUDE
DEPENDPATH += $$INCLUDEPATH $$FRAMEWORK_INSTALL_LIBS

HEADERS += $$QTORM_INCLUDE/*.h

LIBS += -L$$FRAMEWORK_INSTALL_LIBS -l$$QTORM_LIB_NAME
